### ISSUE TITLE
Timezone of Date and Time

### ISSUE THREAD

**Issue by CarstenMaul** [Deutsche-Boerse/dbg-pds#11]
Please add Timezone info to the Data Dictionary, I assume it is UTC?

**Comment by pazaitis** [comment]
I agree with Carsten... It took me some time to understand that it must be UTC. Please add it to the dictionary or to the data itself. Thanks

**Comment by wa793** [comment]
Dear Carsten, pazaitis,

Thank you very much for your feedback. We have added some additional information in section Naming convention.

Kind regards
PDS Team
