### ISSUE TITLE
Clarification required: Column "StartPrice" is referring to what period in intraday files?

### ISSUE THREAD

**Issue by byteburster** [Deutsche-Boerse/dbg-pds#12]
Example: Opening price for DE000ZAL1111 on Xetra today, 2020-10-15, has been 84.58 EUR (according to boerse.ard.de). 

File 2020-10-15_BINS_XETR1029.csv contains this row:
DE000ZAL1111,ZAL,ZALANDO SE,Common stock,EUR,2504863,2020-10-15,10:29,83.78,83.78,83.78,83.78,11,1
where column 9, value 83.78, is supposed to represent the opening value (84.58). Instead it seems to represent the current price.

**Comment by wa793** [comment]
Dear byteburster, 

I would like to kindly inform you that the PDS doesn’t contain the opening price as for an entire trading day.
The PDS contains details for on a per security level, detailing trading activity by minute including the high, low, first and last prices within the time period. In the fore mentioned minute there is only a single trade and thus all columns have the same value: 83.78.
More details may be found here: https://github.com/Deutsche-Boerse/dbg-pds/blob/master/README.md

Kind regards
Your PDS team

**Comment by byteburster** [comment]
Dear PDS team,

thanks for clarification and apologies for my misinterpretation.

Cheers,
byteburster

**Comment by wa793** [comment]
Always welcome! All fine. :)
