### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by axlider** [Deutsche-Boerse/dbg-pds#13]
Hi,

When I try example urls
e.g. curl -H "X-DBP-APIKEY: <INSERT YOUR API KEY HERE>" https://api.developer.deutsche-boerse.com/prod/eurex-public-data-set/1.0.0/eurex
I get: 404 page not found

**Comment by wa793** [comment]
Dear Alexander,
Unfrtunately that service is not being offered anylonger. However, maybe you can check the files which we provide on a daily basis. 

Kind regards,
PDS team
