### ISSUE TITLE
No XETRA data starting from 2020-12-21

### ISSUE THREAD

**Issue by hkq** [Deutsche-Boerse/dbg-pds#14]
Hi there, 

there is no data starting from 2020-12-21. The last data was for 2020-12-18. Can you please check? Thanks in advance!

**Comment by wa793** [comment]
Dear Customer,

Thank you very much for your notification. Can you please check once again? The files should be there now.

Kind regards and staing at your disposal for any further discussions!

**Comment by hkq** [comment]
Hi wa793,

thank you very much! It working again. Very appreciated that you folks are doing this! Keep up the good work!
