### ISSUE TITLE
No new Xetra Data

### ISSUE THREAD

**Issue by koenig-dominik** [Deutsche-Boerse/dbg-pds#9]
The latest Xetra data in the AWS public data was published at 2020-04-09
https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/2020-04-09/2020-04-09_BINS_XETR00.csv --> Exists
https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/2020-04-10/2020-04-10_BINS_XETR00.csv --> Does not exist

**Comment by koenig-dominik** [comment]
Since then some new data was published but is now stuck at 2020-04-30

2020-04-10 - 2020-04-13 are missing.
2020-04-14 - 2020-04-30 exist.
https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/2020-04-30/2020-04-30_BINS_XETR00.csv

But since then no new data was published.
https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/2020-05-01/2020-05-01_BINS_XETR00.csv --> missing
https://s3.eu-central-1.amazonaws.com/deutsche-boerse-xetra-pds/2020-05-28/2020-05-28_BINS_XETR00.csv --> missing

**Comment by wa793** [comment]
hi Dominik, thanks for letting us know. There was some issue that is fixed already. Can you please check again? The min by min/hourly files should be there. Please keep in mind also the public holidays, we have quite some of them in May/June...

**Comment by koenig-dominik** [comment]
Thank you very much for your effort, it works like a charm now!
